ALTER TABLE `commportal`.`USER_ROLES` 
ADD INDEX `FK_ROLE_idx` (`ROLE_ID` ASC);
ALTER TABLE `commportal`.`USER_ROLES` 
ADD CONSTRAINT `FK_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `commportal`.`USER` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_ROLE`
  FOREIGN KEY (`ROLE_ID`)
  REFERENCES `commportal`.`ROLE` (`ROLE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;